import { buildFriendlyName, getUnitTypeCatalog, isUnitTypeStackable } from '../unitDefinitions.js'

const UNIT_TYPE_CATALOG = getUnitTypeCatalog()

function getUnitFriendlyNameTemplate(unitType: string): string | undefined {
	return UNIT_TYPE_CATALOG[unitType as keyof typeof UNIT_TYPE_CATALOG]?.friendlyNameTemplate
}

/** Remove a trailing numeric ordinal from a generated group name. */
export function stripOrdinalSuffix(name: string): string {
	return name.replace(/\s+\d+$/, '')
}

/** Identify names generated by the legacy coordinate-based naming scheme. */
export function isLegacyCoordinateGroupName(name: string): boolean {
	return /\s:\s*-?\d+,-?\d+$/.test(name.trim())
}

/** Build the stable naming key shared by a unit type and board position. */
export function buildStackGroupKey(unitType: string, position: { q: number; r: number }): string {
	return `${unitType}:${position.q},${position.r}`
}

/** Allocate and record the next unused ordinal name for a base label. */
export function createUniqueName(baseName: string, usedNames: Set<string>): string {
	const trimmedBaseName = baseName.trim()
	let suffix = 1
	let candidate = `${trimmedBaseName} ${suffix}`
	while (usedNames.has(candidate)) {
		suffix += 1
		candidate = `${trimmedBaseName} ${suffix}`
	}

	usedNames.add(candidate)
	return candidate
}

/** Resolve a display name from an explicit name, catalog template, or unit id. */
export function resolveStackUnitName(unitType: string, unitId: string | undefined, friendlyName?: string): string {
	const explicitFriendlyName = friendlyName?.trim()
	if (explicitFriendlyName !== undefined && explicitFriendlyName.length > 0) {
		return explicitFriendlyName
	}

	const template = getUnitFriendlyNameTemplate(unitType)
	if (template !== undefined && unitId !== undefined) {
		return buildFriendlyName(template, unitId)
	}

	return unitId ?? unitType
}

/** Resolve the display label for a unit or multi-unit stack. */
export function resolveStackLabel(
	unitType: string,
	unitId: string | undefined,
	friendlyName?: string,
	stackSize = 1,
): string {
	const unitName = resolveStackUnitName(unitType, unitId, friendlyName)

	if (/\sgroup(?:\s+\d+)?$/i.test(unitName)) {
		return unitName
	}

	if (stackSize > 1 || isUnitTypeStackable(unitType)) {
		return `${stripOrdinalSuffix(unitName)} group`
	}

	return unitName
}