CREATE TABLE IF NOT EXISTS users (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  username    VARCHAR(20) NOT NULL,
  email       VARCHAR(254) NOT NULL,
  password_hash TEXT      NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(254);
UPDATE users SET email = 'legacy-' || id::text || '@invalid.local' WHERE email IS NULL;
ALTER TABLE users ALTER COLUMN email SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci_idx ON users (LOWER(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_idx ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS matches (
  id                 INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scenario_id        TEXT        NOT NULL,
  scenario_snapshot  JSONB       NOT NULL,
  host_user_id       UUID        NOT NULL REFERENCES users(id),
  onion_player_id    UUID        REFERENCES users(id),
  defender_player_id UUID        REFERENCES users(id),
  lifecycle_status   TEXT        NOT NULL DEFAULT 'waiting',
  current_phase      TEXT        NOT NULL DEFAULT 'ONION_MOVE',
  turn_number        INTEGER     NOT NULL DEFAULT 1,
  winner             TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS game_state (
  match_id   INTEGER     PRIMARY KEY REFERENCES matches(id) ON DELETE CASCADE,
  state      JSONB       NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS game_events (
  id         BIGSERIAL   PRIMARY KEY,
  match_id   INTEGER     NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  seq        INTEGER     NOT NULL,
  type       TEXT        NOT NULL,
  payload    JSONB       NOT NULL,
  timestamp  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (match_id, seq)
);

CREATE INDEX IF NOT EXISTS idx_game_events_match_seq ON game_events (match_id, seq);

ALTER TABLE matches ADD COLUMN IF NOT EXISTS host_user_id UUID REFERENCES users(id);
ALTER TABLE matches ADD COLUMN IF NOT EXISTS lifecycle_status TEXT NOT NULL DEFAULT 'waiting';
UPDATE matches
SET host_user_id = COALESCE(onion_player_id, defender_player_id)
WHERE host_user_id IS NULL;
UPDATE matches
SET lifecycle_status = CASE
  WHEN winner IS NOT NULL THEN 'completed'
  WHEN onion_player_id IS NOT NULL AND defender_player_id IS NOT NULL THEN 'ready'
  ELSE 'waiting'
END
WHERE lifecycle_status = 'waiting';

ALTER TABLE matches ALTER COLUMN host_user_id SET NOT NULL;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'matches_lifecycle_status_check'
  ) THEN
    ALTER TABLE matches
      ADD CONSTRAINT matches_lifecycle_status_check
      CHECK (lifecycle_status IN ('waiting', 'ready', 'active', 'completed'));
  END IF;
END $$;
